# Generated by Django 5.1.6 on 2025-03-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='users.user')),
            ],
            options={
                'verbose_name': 'Админ',
                'verbose_name_plural': 'Админы',
                'db_table': 'admin_users',
            },
        ),
    ]
