# Generated by Django 5.1.6 on 2025-03-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_plan_amount_chat_message_product_chat_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар (админ)', 'verbose_name_plural': 'Товары (админ)'},
        ),
    ]
