# Generated by Django 5.1.6 on 2025-03-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_product_admin'),
        ('users', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.user'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
