# Generated by Django 5.1.6 on 2025-03-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_product_admin_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
