# Generated by Django 5.1.6 on 2025-03-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
